name: Publish

on:
  push:

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.*
            5.0.*
            6.0.*
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Cache Nuget package dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Build Nuget packages
        run: dotnet build Allure.NUnit/ --configuration Release

      - name: Build Nuget packages
        run: dotnet build Allure.SpecflowPlugin/ --configuration Release
        
      - name: Pack Allure.NUnit
        run: >
          dotnet pack Allure.NUnit/
          --no-build
          --configuration Release
          --output output/packages
          
      - name: Pack Allure.Net.Commons
        run: >
          dotnet pack Allure.Net.Commons/
          -p:TargetFrameworks=netstandard2.0
          --no-build
          --configuration Release
          --output output/packages
         
      - name: Pack Allure.SpecflowPlugin
        run: >
          dotnet pack Allure.SpecflowPlugin/
          --no-build
          --configuration Release
          --output output/packages
          
      - name: Publish Nuget packages
        run: >
          dotnet nuget push output/packages/*.nupkg
          --source "https://nuget.pkg.github.com/dodopizza/index.json"
          --api-key ${{ secrets.GITHUB_TOKEN }} 
          --skip-duplicate